== Browsers Configuration File

Selenoid uses simple JSON configuration files of the following format:

.browsers.json
[source,javascript]
----
{
    "firefox": {                            <1>
      "default": "46.0",                    <2>
      "versions": {                         <3>
        "46.0": {                           <4>
          "image": "selenoid/firefox:46.0", <5>
          "port": "4444",                   <6>
          "tmpfs": {"/tmp": "size=512m"},   <7>
          "path" : "/wd/hub"                <8>
        },
        "50.0" :{
            // ...
        }
      }
    },
    "chrome": {
        // ...
    }
}
----
<1> Browser name
<2> Default browser version
<3> A list of available browser versions
<4> Version name
<5> Image name or driver binary command
<6> _Containers only._ Port to proxy connections to, see below
<7> _Optional. Containers only._ Add in-memory filesystem (_tmpfs_) to container, see below
<8> _Optional._ Path relative to / where we request a new session, see below

This file represents a mapping between a list of supported browser versions and Docker container images or driver binaries.

=== Browser Name and Version
Browser name and version are just strings that are matched against Selenium desired capabilities:

* `browserName`
* `version`

If no version capability is present default version is used. When there is no exact version match we also try to match by prefix.
That means version string in JSON should start with version string from capabilities.

.Matching Logic
====

.in browsers.json
[source,javascript]
----
"versions": {
   "46.0": {
----

Version capability that will match:

`version = 46` (*46.0* starts with *46*)

Will not match:

`version = 46.1` (*46.0* does not start with *46.1*)
====


=== Image
Image by default is a string with container specification in Docker format (`hub.example.com/project/image:tag`).

Image must be already pulled. https://github.com/aerokube/cm[Configuration Manager] can help with this task.

.Valid images
====
Pulled from internal docker registry:

`my-internal-docker-hub.example.com/selenoid/firefox:46.0`

Pulled from hub.docker.com

`selenoid/firefox:46.0`
====

==== Standalone Binary
If you wish to use a standalone binary instead of Docker container, then image field should contain command specification in square brackets:
[source,javascript]
----
"46.0": {
    "image": ["/usr/bin/mybinary", "-arg1", "foo", "-arg2", "bar", "-arg3"],
    "port": "4444"
},
----
Selenoid proxies connections to either Selenium server or standalone driver binary. Depending on operating system both can be packaged inside Docker container.

=== Port, Tmpfs and Path

[source,javascript]
----
"46.0": {
    //...
    "port": ""
    "tmpfs": {"/tmp": "size=512m", "/var": "size=128m"},
    "path" : ""
},
----

 * *port* (_only for containers_) - You should use `port` field to specify the real port inside container that container process (Selenium server, Selenoid or driver) will listen on.

* *tmpfs* (_optional_) - You may probably know that moving browser cache to in-memory filesystem (https://en.wikipedia.org/wiki/Tmpfs[Tmpfs])
can dramatically improve its performance.
Selenoid can automatically attach one or more in-memory filesystems as volumes to Docker container being run.
To achieve this define one or more mount points and their respective sizes in optional `tmpfs` field.

* *path* (_optional_) - The last field - `path` is needed to specify relative path to the URL where a new session is created (default is `/`).
Which value to specify in this field depends on container contents.
For example, most of Firefox containers have http://seleniumhq.org/[Selenium server] inside - thus you need to specify `/wd/hub`.
Chrome and Opera containers use web driver binary as entrypoint application which is accepting requests at `/`.
We recommend to use our https://github.com/aerokube/cm[configuration tool] to avoid errors with this field.

=== Syncing Browser Images from Existing File
In some usage scenarios you may want to store browsers configuration file under version control and initialize Selenoid from this file. For example this is true if you wish to have consistently reproducing infrastructure and using such tools as https://aws.amazon.com/cloudformation/[Amazon Cloud Formation]. In order to pull browser images do the following:

. Install *https://stedolan.github.io/jq/download/[jq]* - a small tool to query data from JSON files.

. Extract image names from JSON and automatically pull them:

    # cat /path/to/browsers.json | jq -r '..|.image|strings' | xargs -I{} docker pull {}
    
