== Browsers Configuration File

Selenoid requires a simple JSON configuration file of the following format:

.browsers.json
[source,javascript]
----
{
    "firefox": {                                     <1>
      "default": "46.0",                             <2>
      "versions": {                                  <3>
        "46.0": {                                    <4>
          "image": "selenoid/firefox:46.0",          <5>
          "port": "4444",                            <6>
          "tmpfs": {"/tmp": "size=512m"},            <7>
          "path" : "/wd/hub",                        <8>
          "volumes" : ["/from:/to:ro"],              <9>
          "env" : ["TZ=Europe/Moscow"],              <10>
          "hosts" : ["example.com:192.168.0.1"],     <11>
          "shmSize" : 268435456,                     <12>
          "cpu" : "1.0",                             <13>
          "mem" : "512m",                            <14>
        },
        "50.0" :{
            // ...
        }
      }
    },
    "chrome": {
        // ...
    }
}
----
<1> Browser name
<2> Default browser version
<3> A list of available browser versions
<4> Version name
<5> Image name or driver binary command
<6> _Containers only._ Port to proxy connections to, see below
<7> _Optional. Containers only._ Add in-memory filesystem (_tmpfs_) to container, see below
<8> _Optional._ Path relative to / where we request a new session, see below
<9> _Optional. Containers only._ Mount path from host machine to created container
<10> _Optional._ Environment variables to be passed to browser container or driver process
<11> _Optional._ Custom `/etc/hosts` entries to be passed to browser container in `hostname:ip` format.
<12> _Optional._ Shared memory size in bytes to be set for container. Some browsers (e.g. Chrome) may work unstable when having insufficient `shmSize`. Default value is 256 megabytes.
<13> _Optional. Containers only._ Container CPU limit in Docker units.
<14> _Optional. Containers only._ Container memory limit in Docker units.

This file represents a mapping between a list of supported browser versions and Docker container images or driver binaries.

[NOTE]
====
To use custom browsers configuration file - use `-conf` flag:

    $ ./selenoid -conf /path/to/browsers.json
====

=== Browser Name and Version
Browser name and version are just strings that are matched against Selenium desired capabilities:

* `browserName`
* `version`

If no version capability is present default version is used. When there is no exact version match we also try to match by prefix.
That means version string in JSON should start with version string from capabilities.

.Matching Logic
====

.in browsers.json
[source,javascript]
----
"versions": {
   "46.0": {
----

Version capability that will match:

`version = 46` (*46.0* starts with *46*)

Will not match:

`version = 46.1` (*46.0* does not start with *46.1*)
====


=== Image
Image by default is a string with container specification in Docker format (`hub.example.com/project/image:tag`).

Image must be already pulled. https://github.com/aerokube/cm[Configuration Manager] can help with this task.

.Valid images
====
Pulled from internal docker registry:

`my-internal-docker-hub.example.com/selenoid/firefox:46.0`

Pulled from hub.docker.com

`selenoid/firefox:46.0`
====

==== Standalone Binary
If you wish to use a standalone binary instead of Docker container, then image field should contain command specification in square brackets:
[source,javascript]
----
"46.0": {
    "image": ["/usr/bin/mybinary", "-arg1", "foo", "-arg2", "bar", "-arg3"],
    "port": "4444"
},
----
Selenoid proxies connections to either Selenium server or standalone driver binary. Depending on operating system both can be packaged inside Docker container.

=== Other Optional Fields

[source,javascript]
----
"46.0": {
    //...
    "port": "",
    "tmpfs": {"/tmp": "size=512m", "/var": "size=128m"},
    "path" : "",
    "volumes": ["/from:/to", "/another:/one:ro"],
    "env" : ["TZ=Europe/Moscow", "ONE_MORE_VARIABLE=itsValue"],
    "hosts" : ["one.example.com:192.168.0.1", "two.example.com:192.168.0.2"],
    "labels" : {"component": "frontend", "project": "my-project"},
    "sysctl" : {"net.ipv4.tcp_timestamps": "2", "kern.maxprocperuid": "1000"},
    "shmSize" : 268435456,
},
----

* *port* (_only for containers_) - You should use `port` field to specify the real port inside container that container process (Selenium server, Selenoid or driver) will listen on.

* *tmpfs* (_optional_) - You may probably know that moving browser cache to in-memory filesystem (https://en.wikipedia.org/wiki/Tmpfs[Tmpfs])
can dramatically improve its performance.
Selenoid can automatically attach one or more in-memory filesystems as volumes to Docker container being run.
To achieve this define one or more mount points and their respective sizes in optional `tmpfs` field.

* *path* (_optional_) - `path` field is needed to specify relative path to the URL where a new session is created (default is `/`).
Which value to specify in this field depends on container contents.
For example, most of Firefox containers have http://seleniumhq.org/[Selenium server] inside - thus you need to specify `/wd/hub`.
Chrome and Opera containers use web driver binary as entrypoint application which is accepting requests at `/`.
We recommend to use our https://github.com/aerokube/cm[configuration tool] to avoid errors with this field.

* *volumes* (_optional_) - This field allows to mount volumes from host machine to browser container. Should be specified as an array of Docker volume expressions: `/host/dir:/container/dir[:mode]`.

* *env* (_optional_) - This field allows to set any environment variables in running container. Specified as an array of `NAME=value` pairs.

* *hosts* (_optional_) - This field allows to add custom `/etc/hosts` entries to running container. Specified as an array of `hostname:ip` pairs.

* *labels* (_optional_) - This field allows to add custom labels to running container. Specified as an object of `"key": "value"` pairs.

* *sysctl* (_optional_) - This field allows to adjust kernel parameters of running container. Specified as an object of `"key": "value"` pairs.

* *shmSize* (_optional_) - Use it to override shared memory size for browser container.

=== Syncing Browser Images from Existing File
In some usage scenarios you may want to store browsers configuration file under version control and initialize Selenoid from this file. For example this is true if you wish to have consistently reproducing infrastructure and using such tools as https://aws.amazon.com/cloudformation/[Amazon Cloud Formation].

NOTE: Why this is not the part of Selenoid? Well, this is easy to implement, but under heavy load the result can be unpredictable.
For example after updating the file and reloading Selenoid it should pull new images. How long will you wait for new sessions then?
What to do if Docker Registry is inaccessible? So for maintenance reasons it is easier to delegate such simple logic to external script.

In order to pull browser images use on of the following options:

*Option 1: using CM*

Recent https://github.com/aerokube/cm[CM] tool versions are able to configure Selenoid from existing `browsers.json` file as follows:

    # ./cm selenoid start --browsers-json /path/to/your/browsers.json

This way is mainly useful when installing Selenoid from scratch or updating it i.e. as a part of CI build job.

*Option 2: using jq*

. Install *https://stedolan.github.io/jq/download/[jq]* - a small tool to query data from JSON files.

. Extract image names from JSON and automatically pull them:

    # cat /path/to/browsers.json | jq -r '..|.image?|strings' | xargs -I{} docker pull {}

This way can be applied to a running cluster with tests with no downtime.
