== Recommended Docker Settings

* We recommend to use latest Docker release and Linux core 4.x and above. Older kernels and Docker releases have known bugs.
* Use modern https://en.wikipedia.org/wiki/OverlayFS[OverlayFS] Docker storage driver. https://en.wikipedia.org/wiki/Aufs[AUFS] is also fast but has some bugs that can lead to orphaned containers. Never use https://en.wikipedia.org/wiki/Device_mapper[Device Mapper] - it is very slow. See https://docs.docker.com/engine/userguide/storagedriver/selectadriver/[this] page on how to adjust Docker storage driver. To check your currently used driver type:
+
```
# docker info | grep Storage
```
* Total number of simultaneously running containers (adjusted via ```-limit``` flag) depends on your host machine hardware. Our experience shows that depending on your tests the recommended limit is something like: ```1.5-2.0 x numCores```, where ```numCores``` is total number of cores on your host machine.
* In some Docker installations you can see random Selenium commands failing because of the timeout. This is mainly caused by low bridged networking (aka `docker0`) performance. To avoid this we recommend to set `docker0` network Mac-address to the same value as `eth0` has:

    # ifconfig | grep eth0
    eth0      Link encap:Ethernet  HWaddr 00:25:90:eb:fb:3e
+
Now we are setting this Mac-adress for `docker0` virtual interface:  
    
    # ip link set docker0 address 00:25:90:eb:fb:3e

+
To make these settings permanent we need to adding the following line to `docker0` section in `/etc/network/interfaces`:

    iface docker0 inet static
            # ... the rest of lines
            post-up ip link set docker0 address 00:25:90:eb:fb:3e
    
* You may also want to limit memory and CPU consumption for each started container. To do this use ```-mem``` and ```-cpu``` flags. For example to limit memory type:

    # ./selenoid -mem 128m
+
Here values are specified in https://docs.docker.com/engine/admin/resource_constraints/[Docker format]. Similarly to limit CPU comsumption specify total number of CPUs per container as a float:

    # ./selenoid -cpu 1.5
    
* We use the same client as `docker` command does. This is why all environment variables like `DOCKER_API_VERSION` or `DOCKER_CERT_PATH` are applicable. See full list of supported variables in https://docs.docker.com/engine/reference/commandline/cli/#environment-variables[Docker documentation]. For example you may encounter the following error when running Selenoid:
    
    [SERVICE_STARTUP_FAILED] [unknown] [create container: Error response from daemon: client is newer than server (client API version: 1.30, server API version: 1.24)]
+    
This is because your Docker server version is older than Selenoid client version. To fix this you need to switch Selenoid to use supported API version - `1.24`. This can be done by setting `DOCKER_API_VERSION` environment variable:

    # docker run -e DOCKER_API_VERSION=1.24 -d --name selenoid -p 4444:4444 -v /etc/selenoid:/etc/selenoid:ro -v /var/run/docker.sock:/var/run/docker.sock aerokube/selenoid:latest-release
