== Quick Start Guide
. Download and run http://aerokube.com/cm/latest/[Configuration Manager] from https://github.com/aerokube/cm/releases/latest[releases] page.
+
**On Linux:**

    $ curl -L -o cm https://github.com/aerokube/cm/releases/download/1.2.4/cm_linux_amd64
    $ chmod +x ./cm
    $ ./cm selenoid start --vnc

+
**On Mac:**

    $ curl -L -o cm https://github.com/aerokube/cm/releases/download/1.2.4/cm_darwin_amd64
    $ chmod +x ./cm
    $ ./cm selenoid start --vnc

+
**On Windows** - just download the binary with your browser or if you have https://en.wikipedia.org/wiki/PowerShell[Powershell] type:

    > curl -L -o cm.exe https://github.com/aerokube/cm/releases/download/1.2.4/cm_windows_amd64
    > ./cm.exe selenoid start --vnc

+
[NOTE]
====
. If you have https://docs.docker.com/engine/installation/[Docker] installed you can also use this one-liner:
[source,bash,subs="attributes+"]
# docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v ${HOME}:/root -e OVERRIDE_HOME=${HOME} aerokube/cm:latest-release selenoid start --vnc --tmpfs 128

. If you are working behind proxy you should set environment variables `HTTP_PROXY`, `HTTPS_PROXY` or `NO_PROXY` described in https://docs.docker.com/engine/admin/systemd/#runtime-directory-and-storage-driver[Docker documentation]:
[source,bash,subs="attributes+"]
$ HTTP_PROXY=http://proxy.example.com:80/ ./cm selenoid start
+
When running `cm` in container - pass variable via `-e` flag of the `docker` command. These variables work because `cm` is using the same client as `docker` command.
====

. Run your tests against Selenoid like you do with regular Selenium hub:

    http://localhost:4444/wd/hub

. Selenoid was created to be run in big Selenium clusters and thus has no built-in user interface. This is why trying to open an URL above in browser returns *404* and this is the expected behavior. If something does not work, you can easily check that Selenoid is running with `curl`:

    $ curl http://localhost:4444/status

+
A successful request should return a JSON with browser usage statistics. 
. You can additionally use http://github.com/aerokube/selenoid-ui[Selenoid UI] to see browser screen or consumption statistics. The simplest way is to download and run its binary from https://github.com/aerokube/selenoid-ui/releases[releases] page and start it:

    $ ./selenoid-ui

+
See http://aerokube.com/selenoid-ui/latest/[UI documentation] for more installation options. By default UI is listening on port 8080. To start using it open the following page in your browser:

    http://localhost:8080/

