== Quick Start Guide

[TIP]
====
The fastest way to start Selenoid is to use http://aerokube.com/cm/latest/[Configuration Manager]. Just download the binary for your platform
from https://github.com/aerokube/cm/releases/latest[releases] page and run one command:

----
./cm selenoid start --vnc
----

Running this command will configure and start Selenoid automatically. Please refer to corresponding http://aerokube.com/cm/latest/[Quick Start with Configuration Manager] section for more details.
====

This guide shows how to start Selenoid manually. When in doubt take a look at Configuration Manager first.

WARNING: This guide assumes you already know how to deal with command line and know basic Docker commands.

=== Prepare Configuration

. Create `config/browsers.json` configuration file with content:
+
.config/browsers.json
[source,javascript]
----
{
    "firefox": {
        "default": "57.0",
        "versions": {
            "57.0": {
                "image": "selenoid/vnc:firefox_57.0",
                "port": "4444",
                "path": "/wd/hub"
            }
        }
    }
}
----
+
NOTE: For Chrome and Opera images "path" is "/" instead of "/wd/hub"
+
. Pull browser Docker image:
+
`$ docker pull selenoid/vnc:firefox_57.0`.

=== Start Selenoid
==== Option 1: start Selenoid binary

. Download binary for your operating system from https://github.com/aerokube/selenoid/releases/latest[releases] page
and save it as `selenoid` (or `selenoid.exe` on windows).
+
NOTE: Add execution permission in case of *nix os-type with `chmod +x selenoid`.

. Then run:
+
.*nix
----
./selenoid
----
+
.Windows
----
selenoid.exe
----

. It should write to console something like:
+
----
2017/11/26 21:23:43 Loading configuration files...
2017/11/26 21:23:43 Loaded configuration from [config/browsers.json]

...

2017/11/26 21:23:43 Listening on :4444
----

==== Option 2: start Selenoid container

If you have https://docs.docker.com/engine/installation/[Docker] installed you can omit downloading binary and run it inside container.
Prepare config, pull browser image, then run:

.*nix
[source,bash,subs="attributes+"]
----
docker run -d                                   \
--name selenoid                                 \
-p 4444:4444                                    \
-v /var/run/docker.sock:/var/run/docker.sock    \
-v `pwd`/config/:/etc/selenoid/:ro              \
aerokube/selenoid:latest-release
----

.Windows PowerShell
[source,bash,subs="attributes+"]
----
> $current = $PWD -replace "\\", "/" -replace "C", "c"  <1>
> docker run -d                                         `
--name selenoid                                         `
-p 4444:4444                                            `
-v //var/run/docker.sock:/var/run/docker.sock           `
-v ${current}/config/:/etc/selenoid/:ro                 `
aerokube/selenoid:latest-release
----
<1> Simple macros to get $PWD with compatible form assumed your directory located on `C:` drive


=== Run Your Tests

Run your tests against Selenoid like you do with regular Selenium hub:

.Tests Endpoint
----
http://localhost:4444/wd/hub
----

NOTE: Selenoid was created to be run in big Selenium clusters and thus has no built-in user interface. This is why trying to open an URL above in browser returns *404* and this is the expected behavior.

If something does not work, you can easily check that Selenoid is running with opening *status* url:

.Current Selenoid Status
----
http://localhost:4444/status
----

A successful request should return a JSON with browser usage statistics. You can additionally use http://github.com/aerokube/selenoid-ui[Selenoid UI] to see browser screen or consumption statistics.
The simplest way is to download and run its binary from https://github.com/aerokube/selenoid-ui/releases[releases] page and start it:

----
./selenoid-ui
----

See http://aerokube.com/selenoid-ui/latest/[UI documentation] for more installation options.
By default UI is listening on port 8080. To start using it open the following page in your browser:

.UI Default URL
----
http://localhost:8080/
----

