== Using Selenoid without Docker

Selenoid is using containers to start browsers. However cases exist when running browser in container is not possible. For example on Windows you have Internet Explorer which can not be run inside container. Selenoid can be used as a lightweight Selenium server replacement to run IE, Firefox or Chrome on Windows. For example to use Selenoid with IE:

. Download latest http://www.seleniumhq.org/download/[IEDriverServer] archive and unpack it to some directory (```C:\``` in this example).
. Download latest https://github.com/aerokube/selenoid/releases/latest[Selenoid] binary.
. Create ```browsers.json``` configuration file:
+
```json
{
  "internet explorer": {
    "default": "11",
    "versions": {
      "11": {
        "image": ["C:\\IEDriverServer.exe", "--log-level=DEBUG"]
      }
    }
  }
}
```
+
Notice that backslashes in Windows paths should be escaped as ```\\```.
In this example we define a browser with name ```internet explorer```  and version ```11```.
. Start Selenoid:
+
```
./selenoid_win_amd64.exe -conf ./browsers.json -disable-docker
```
. Run your tests against \...
+
```
http://localhost:4444/wd/hub
```
+
\... with the following capabilities:
+
```
browserName = internet explorer
version = 11
```
. To start https://www.google.com/chrome/[Chrome] instead just download https://sites.google.com/a/chromium.org/chromedriver/[Chromedriver] binary and modify ```browsers.json``` accordingly.
. By default Selenoid does not process launched driver logs. Launch Selenoid with `-capture-driver-logs` flag to append driver logs for every session to main log. 