== Special Capabilities

Selenoid can improve some automation aspects with custom capabilities.
You can pass it in tests to enable/disable some features.


=== Live Browser Screen: enableVNC

Selenoid supports showing browser screen during test execution.
This works with containers having https://en.wikipedia.org/wiki/Virtual_Network_Computing[VNC] server installed (VNC column of <<Browser Image information>>).
To see browser screen:

.Type: boolean
----
enableVNC: true
----

Then launch http://aerokube.com/selenoid-ui/latest/[Selenoid UI] to see the screen.

This works by proxying VNC port from started container to `http://localhost:4444/vnc/<session-id>` to WebSocket, where `<session-id>` is Selenium session ID.

=== Custom Screen Resolution: screenResolution

Selenoid allows you to set custom screen resolution in containers being run:

.Type: string, format: <width>x<height>x<colors-depth>
----
screenResolution: "1280x1024x24"
----
[WARNING]
====
- This capability sets only screen resolution - not browser window size.
Most of browsers have some default window size value this is why your screenshot size can be smaller than screen resolution specified in capability.
You should manually resize window to desired width and height.

- So far as our containers run headless browsers in Xvfb without installed window manager `maximize` operation does not work.
You need to use `setSize` method instead.
====

=== Video Recording: enableVideo, videoName, videoScreenSize, videoFrameRate

NOTE: This feature requires some preparation. Please refer <<Video Recording>> section for details.

To enable video recording for session, add:

.Type: boolean
----
enableVideo: true
----

* By default files are named `<session-id>.mp4` where `<session-id>` is a unique identifier of Selenium session.
To provide custom video name specify:
+
.Type: string
----
videoName: "my-cool-video.mp4"
----
+
WARNING: It is important to add `mp4` file extension.

* By default the entire screen picture is being recorded.
Specifying `screenResolution` capability changes recorded video size (width and height) accordingly.
You can override video screen size by passing a capability. In case of `videoScreenSize`
resolution is less than actual, screen on video will be trimmed starting from top-left corner:
+
.Type: string
----
videoScreenSize: "1024x768"
----

* Default video frame rate is `12` frames per second. Specifying `videoFrameRate` capability changes this value:
+
.Type: int
----
videoFrameRate: 24
----

=== Custom Test Name: name

For debugging purposes it is often useful to give a distinct name to every test case.
When working with Selenoid you can set test case name by passing the following capability:

.Type: string
----
name: "myCoolTestName"
----

The main application of this capability - is debugging tests in the UI which is showing specified name for every running session.

=== Per-session Time Zone: timeZone

Some tests require particular time zone to be set in operating system.
To achieve this with Selenoid use:

.Type: string
----
timeZone: "Europe/Moscow"
----

You can find most of available time zones https://en.wikipedia.org/wiki/List_of_tz_database_time_zones[here].
Without this capability launched browser containers will have the same timezone as Selenoid one.

=== Links to Application Containers: applicationContainers

Sometimes you may need to link browser container to application container running on the same host machine.
This allows you to use cool URLs like `http://my-cool-app/` in tests.
To achieve this simply pass information about one or more desired links via capability:

.Type: string, format: <container-name>[:alias] (comma-separated)
----
applicationContainers: "spring-application-main:my-cool-app,spring-application-gateway"
----

=== Hosts Entries: hostsEntries

Although you can configure a separate list of `/etc/hosts` entries for every browser image in <<Browsers Configuration File>>
sometimes you may need to add more entries for particular test cases. This can be easily achieved with:

.Type: string, format: <hostname>:<ip-address> (comma-separated)
----
hostsEntries: "example.com:192.168.0.1,test.com:192.168.0.2"
----

Entries will be inserted to `/etc/hosts` before entries from browsers configuration file.
Thus entries from capabilities override entries from configuration file if some hosts are equal.
