== Special Capabilities

=== Live Browser Screen

Selenoid supports showing browser screen during test execution. This works with containers having https://en.wikipedia.org/wiki/Virtual_Network_Computing[VNC] server installed. To see browser screen:

. Pass ```enableVNC``` capability in tests:
+
```
enableVNC = true
```
. Launch http://aerokube.com/selenoid-ui/latest/[Selenoid UI] to see the screen.

This works by proxying VNC port from started container to ```http://localhost:4444/vnc/<session-id>``` where ```<session-id>``` is Selenium session ID.

=== Custom Screen Resolution

Selenoid allows you to set custom screen resolution in containers being run. To do that simply pass ```screenResolution``` capability in your tests in form ```width x height x color-depth```:

```
screenResolution: 1280x1024x24
```
[NOTE]
====
. This capability sets only screen resolution - not browser window size. Most of browsers have some default window size value this is why your screenshot size can be smaller than screen resolution specified in capability. You should manually resize window to desired width and height.

. So far as our containers run headless browsers in Xvfb without installed window manager `maximize` operation does not work. You need to use `setSize` method instead.
====

=== Custom Test Name

For debugging purposes it is often useful to give a distinct name to every test case. When working with Selenoid you can set test case name by passing the following capability:
```
name: myCoolTestName
```
The main application of this capability - is debugging tests in the UI which is showing specified name for every running session.

=== Per-session Time Zone

Some tests require particular time zone to be set in operating system. To achieve this with Selenoid simply set one more capability:
```
timeZone: Europe/Moscow
```
You can find most of available time zones https://en.wikipedia.org/wiki/List_of_tz_database_time_zones[here]. Without this capability launched browser containers will have the same timezone as Selenoid one.

=== Links to Application Containers

Sometimes you may need to link browser container to application container running on the same host machine. This allows you to use cool URLs like `http://my-cool-app/` in tests. To achieve this simply pass information about one or more desired links via capability:
```
applicationContainers: my-app:some-alias,another-app
```
Links are specified as a comma-separated list of `<name>[:<alias>]` pairs. 

=== Hosts Entries

Although you can configure a separate list of `/etc/hosts` entries for every browser image in <<Browsers Configuration File>> sometimes you may need to add more entries for particular test cases. This can be easily achieved by passing a capability:
```
hostsEntries: "example.com:192.168.0.1,test.com:192.168.0.2"
```
This capability represents a comma-separated list of `<hostname>:<ip-address>` entries to be added to `/etc/hosts`. Entries from capabilities are inserted to `/etc/hosts` before entries from browsers configuration file. Thus entries from capabilities override entries from configuration file if some hosts are equal.