== Special Capabilities

=== Live Browser Screen

Selenoid supports showing browser screen during test execution. This works with containers having https://en.wikipedia.org/wiki/Virtual_Network_Computing[VNC] server installed. To see browser screen:

. Pass ```enableVNC``` capability in tests:
+
```
enableVNC = true
```
. Launch http://aerokube.com/selenoid-ui/latest/[Selenoid UI] to see the screen.

This works by proxying VNC port from started container to ```http://localhost:4444/vnc/<session-id>``` where ```<session-id>``` is Selenium session ID.

=== Custom Screen Resolution

Selenoid allows you to set custom screen resolution in containers being run. To do that simply pass ```screenResolution``` capability in your tests in form ```width x height x color-depth```:

```
screenResolution: 1280x1024x24
```
[NOTE]
====
. This capability sets only screen resolution - not browser window size. Most of browsers have some default window size value this is why your screenshot size can be smaller than screen resolution specified in capability. You should manually resize window to desired width and height.

. So far as our containers run headless browsers in Xvfb without installed window manager `maximize` operation does not work. You need to use `setSize` method instead.
====

=== Custom Test Name

For debugging purposes it is often useful to give a distinct name to every test case. When working with Selenoid you can set test case name by passing the following capability:
```
name: myCoolTestName
```
The main application of this capability - is debugging tests in the UI which is showing specified name for every running session.