== Special Capabilities

Selenoid can improve some automation aspects with custom capabilities.
You can pass it in tests to enable/disable some features.


=== Live Browser Screen: enableVNC

Selenoid supports showing browser screen during test execution.
This works with containers having https://en.wikipedia.org/wiki/Virtual_Network_Computing[VNC] server installed (VNC column of <<Browser Image information>>).
To see browser screen:

.Type: boolean
----
enableVNC: true
----

Then launch http://aerokube.com/selenoid-ui/latest/[Selenoid UI] to see the screen.

This works by proxying VNC port from started container to `http://localhost:4444/vnc/<session-id>` to WebSocket, where `<session-id>` is Selenium session ID.

=== Custom Screen Resolution: screenResolution

Selenoid allows you to set custom screen resolution in containers being run:

.Type: string, format: <width>x<height>x<colors-depth>
----
screenResolution: "1280x1024x24"
----
[WARNING]
====
- This capability sets only screen resolution - not browser window size.
Most of browsers have some default window size value this is why your screenshot size can be smaller than screen resolution specified in capability.
You should manually resize window to desired width and height.

- So far as our containers run headless browsers in Xvfb without installed window manager `maximize` operation does not work.
You need to use `setSize` method instead.
====

=== Video Recording: enableVideo, videoName, videoScreenSize, videoFrameRate

NOTE: This feature requires some preparation. Please refer to <<Video Recording>> section for details.

To enable video recording for session, add:

.Type: boolean
----
enableVideo: true
----

* By default files are named `<session-id>.mp4` where `<session-id>` is a unique identifier of Selenium session.
To provide custom video name specify:
+
.Type: string
----
videoName: "my-cool-video.mp4"
----
+
WARNING: It is important to add `mp4` file extension.

* By default the entire screen picture is being recorded.
Specifying `screenResolution` capability changes recorded video size (width and height) accordingly.
You can override video screen size by passing a capability. In case of `videoScreenSize`
resolution is less than actual, screen on video will be trimmed starting from top-left corner:
+
.Type: string
----
videoScreenSize: "1024x768"
----

* Default video frame rate is `12` frames per second. Specifying `videoFrameRate` capability changes this value:
+
.Type: int
----
videoFrameRate: 24
----

=== Custom Test Name: name

For debugging purposes it is often useful to give a distinct name to every test case.
When working with Selenoid you can set test case name by passing the following capability:

.Type: string
----
name: "myCoolTestName"
----

The main application of this capability - is debugging tests in the UI which is showing specified name for every running session.

=== Per-session Time Zone: timeZone

Some tests require particular time zone to be set in operating system.
To achieve this with Selenoid use:

.Type: string
----
timeZone: "Europe/Moscow"
----

You can find most of available time zones https://en.wikipedia.org/wiki/List_of_tz_database_time_zones[here].
Without this capability launched browser containers will have the same timezone as Selenoid one.

=== Per-session Environment Variables: env

Sometimes you may want to set some environment variables for every test case (for example to test with different default locales). To achieve this pass one more capability: 

.Type: array, format: <key>=<value>
----
env: ["LANG=ru_RU.UTF-8", "LANGUAGE=ru:en", "LC_ALL=ru_RU.UTF-8"]
----

Environment variables from this capability are appended to variables from configuration file.

=== Links to Application Containers: applicationContainers

Sometimes you may need to link browser container to application container running on the same host machine.
This allows you to use cool URLs like `http://my-cool-app/` in tests.
To achieve this simply pass information about one or more desired links via capability:

.Type: array, format: <container-name>[:alias] 
----
applicationContainers: ["spring-application-main:my-cool-app", "spring-application-gateway"]
----

=== Hosts Entries: hostsEntries

Although you can configure a separate list of `/etc/hosts` entries for every browser image in <<Browsers Configuration File>>
sometimes you may need to add more entries for particular test cases. This can be easily achieved with:

.Type: array, format: <hostname>:<ip-address>
----
hostsEntries: ["example.com:192.168.0.1", "test.com:192.168.0.2"]
----

Entries will be inserted to `/etc/hosts` before entries from browsers configuration file.
Thus entries from capabilities override entries from configuration file if some hosts are equal.

=== Container Labels: labels

In big clusters you may want to pass additional metadata to every browser session: environment, VCS revision, build number and so on. These labels can be then used to enrich session logs and send them to a centralized log storage. Later this metadata can be used for more efficient search through logs. 

.Type: map, format: "<key>": "<value>"
----
labels: {"environment": "testing", "build-number": "14353"]
----

Labels from this capability override labels from browsers configuration file. When `name` capability is specified - it is automatically added as a label to container.

=== Specifying Capabilities via Protocol Extensions

Some Selenium clients allow passing only a limited number of capabilities specified in https://w3c.github.io/webdriver/webdriver-spec.html[WebDriver specification]. For such cases Selenoid supports reading capabilities using https://w3c.github.io/webdriver/webdriver-spec.html#protocol-extensions[WebDriver protocol extensions] feature. The following two examples deliver the same result. Usually capabilities are passed like this:

.Passing Capabilities as Usually
----
{"browserName": "firefox", "version": "57.0", "screenResolution": "1280x1024x24"}
----

Selenoid is using `selenoid:options` key to read protocol extension capabilities:

.Passing Capabilities using Protocol Extensions
----
{"browserName": "firefox", "version": "57.0", "selenoid:options": {"screenResolution": "1280x1024x24"}}
----