== Video Recording
NOTE: This feature only works when browsers are run in containers. This can be both vnc or non-vnc containers.

Selenoid can capture browser screen and save it to https://en.wikipedia.org/wiki/MPEG-4[MPEG-4] video file using https://en.wikipedia.org/wiki/H.264/MPEG-4_AVC[H264] codec.
Video recording works by attaching a separate container with https://www.ffmpeg.org/[video capturing software] to running browser container.

To setup this feature you should:

. Pull video recorder image once: `docker pull selenoid/video-recorder`

*Without docker* videos will be stored in `video` directory, relative to binary.

*With docker*:

. Mount host directory for video to `/opt/selenoid/video/` (this is default value for `video-output-dir` selenoid arg in docker)
. Pass an additional `OVERRIDE_VIDEO_OUTPUT_DIR` environment variable with absolute path to video directory on host machine.
  This is required because of video recorder, created by selenoid should know about host mount point, but not selenoid's one.
  (Selenoid and video recorder connected via host)

NOTE: This environment variable thing can be changed in future if we will find a way to link to selenoid volume directly.

.Example
----
$ docker run -d
--name selenoid                                 \
-p 4444:4444                                    \
-v /var/run/docker.sock:/var/run/docker.sock    \
-v `pwd`/config/:/etc/selenoid/:ro              \
-v `pwd`/video/:/opt/selenoid/video/            \
-e OVERRIDE_VIDEO_OUTPUT_DIR=`pwd`/video/       \
aerokube/selenoid:latest-release
----

TIP: All this stuff is automated by http://aerokube.com/cm/latest/[Configuration Manager] `selenoid start` command

=== On Windows

With absolute path your command will look like:

.Windows PowerShell
[source,bash,subs="attributes+"]
----
> docker volume create selenoid-videos
> $current = $PWD -replace "\\", "/" -replace "C", "c"    <1>
> docker run -d                                         `
--name selenoid                                         `
-p 4444:4444                                            `
-v //var/run/docker.sock:/var/run/docker.sock           `
-v ${current}/config/:/etc/selenoid/:ro                 `
-v /c/selenoid/video/:/opt/selenoid/video/              ` <2>
-e OVERRIDE_VIDEO_OUTPUT_DIR=/c/selenoid/video/         ` <3>
aerokube/selenoid:latest-release
----
<1> Simple macros to get $PWD with compatible form assumed your directory located on `C:` drive
<2> Should be absolute path in compatible form
<3> Should be same as in (2)


==== Video files access with Selenoid

You can access recorded video files using the following URL:

.Direct link to file
----
http://selenoid-host.example.com:4444/video/<filename>.mp4
----

NOTE: Direct link will work only after session finish as of selenoid renames random filename to `<session-id>.mp4` (by default) at the session close.

To see all available files use:

.All video files list
----
http://selenoid-host.example.com:4444/video/
----
