== Selenoid under Windows

While we normally recommend to start Selenoid using http://aerokube.com/cm/latest[Configuration Manager] on any platform,
it is possible to start it under Windows manually.

NOTE: Most of the differences are related to Docker, so please refer to Docker documentation on any errors first.

The main difference from Unix operating systems is how volumes are mounted.
In any Windows paths back slashes (`\`) should be replaced by forward slashes (`/`) and drive letter should be lower cased.
Also start with forward slash and remove colon.

.Mount directory
====
`C:\Users\admin` becomes `/c/Users/admin`
====

NOTE: Another story with `docker.sock`, which should be mounted as `-v //var/run/docker.sock:/var/run/docker.sock` (note two forward slashes at the beginning)

So assuming that configuration file is located at `C:\Users\admin\selenoid` a typical startup command can look like:

----
docker run -d --name selenoid                   `
-p 4444:4444                                    `
-v //var/run/docker.sock:/var/run/docker.sock   `
-v /c/Users/admin/selenoid:/etc/selenoid:ro                 `
aerokube/selenoid:latest-release
----

[TIP]
====
You can use simple Powershell macros to automatically get correct `$PWD` value (assumed you are on `C:`):

----
> $current = $PWD -replace "\\", "/" -replace "C", "c"
----
====

